data_cfg:
  dataset_name: SUSTech1K
  dataset_root: your_path/SUSTech1K-pkl
  dataset_partition: ./datasets/SUSTech1K/SUSTech1K.json
  num_workers: 4
  data_in_use: [false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false]
  remove_no_gallery: false
  test_dataset_name: SUSTech1K

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: 50000
  save_name: GaitBase_SUSTech1K_SilsAligned
  eval_func: evaluate_indoor_dataset
  sampler:
    batch_shuffle: false
    batch_size: 1
    sample_type: all_ordered
    frames_all_limit: 720
  metric: euc
  transform:
    - type: BaseSilCuttingTransform
      img_w: 64
  save_embeddings: true
  save_embeddings_dir: embeddings

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 16
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true

model_cfg:
  model: Baseline
  backbone_cfg:
    type: ResNet9
    block: BasicBlock
    channels:
      - 64
      - 128
      - 256
      - 512
    layers:
      - 1
      - 1
      - 1
      - 1
    strides:
      - 1
      - 2
      - 2
      - 1
    maxpool: false
  SeparateFCs:
    in_channels: 512
    out_channels: 256
    parts_num: 16
  SeparateBNNecks:
    class_num: 1058
    in_channels: 256
    parts_num: 16
  bin_num:
    - 16

optimizer_cfg:
  lr: 0.1
  momentum: 0.9
  solver: SGD
  weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones:
    - 20000
    - 30000
    - 40000
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true
  fix_BN: false
  with_test: true
  log_iter: 1000
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 10000
  save_name: GaitBase_SUSTech1K_SilsAligned
  sync_BN: true
  total_iter: 50000
  sampler:
    batch_shuffle: true
    batch_size:
      - 6
      - 6
    frames_num_fixed: 10
    sample_type: fixed_unordered
    type: TripletSampler
  transform:
    - type: Compose
      trf_cfg:
        - type: RandomPerspective
          prob: 0.2
        - type: BaseSilCuttingTransform
          img_w: 64
        - type: RandomHorizontalFlip
          prob: 0.2
        - type: RandomRotate
          prob: 0.2
