data_cfg:
  dataset_name: Scoliosis1K
  dataset_root: your_path/Scoliosis1K-DRF-pkl
  dataset_partition: ./datasets/Scoliosis1K/Scoliosis1K_114.json
  data_in_use: [true, true]
  cache: false
  num_workers: 1
  remove_no_gallery: false
  test_dataset_name: Scoliosis1K

evaluator_cfg:
  enable_float16: true
  restore_ckpt_strict: true
  restore_hint: 16000
  save_name: DRF_114_weighted_clstriplet_20000
  eval_func: evaluate_scoliosis
  sampler:
    batch_size: 1
    sample_type: all_ordered
    frames_all_limit: 720
    type: InferenceSampler
  metric: euc
  transform:
    - type: BaseSilCuttingTransform
    - type: NoOperation

loss_cfg:
  - loss_term_weight: 1.0
    margin: 0.2
    type: TripletLoss
    log_prefix: triplet
  - loss_term_weight: 1.0
    scale: 16
    class_weight: [0.333, 1.3335, 1.3335]
    type: CrossEntropyLoss
    log_prefix: softmax
    log_accuracy: true

model_cfg:
  model: DRF
  triplet_label: class
  backbone_cfg:
    type: ResNet9
    block: BasicBlock
    in_channel: 2
    channels: [64, 128, 256, 512]
    layers: [1, 1, 1, 1]
    strides: [1, 2, 2, 1]
    maxpool: false
  SeparateFCs:
    in_channels: 512
    out_channels: 256
    parts_num: 16
  SeparateBNNecks:
    class_num: 3
    in_channels: 256
    parts_num: 16
  bin_num: [16]
  pav_pair_num: 8
  pav_metric_num: 3

optimizer_cfg:
  lr: 0.1
  momentum: 0.9
  solver: SGD
  weight_decay: 0.0005

scheduler_cfg:
  gamma: 0.1
  milestones: [10000, 14000, 18000]
  scheduler: MultiStepLR

trainer_cfg:
  enable_float16: true
  find_unused_parameters: false
  fix_BN: false
  with_test: false
  log_iter: 100
  optimizer_reset: false
  scheduler_reset: false
  restore_ckpt_strict: true
  restore_hint: 0
  save_iter: 1000
  save_name: DRF_114_weighted_clstriplet_20000
  sync_BN: true
  total_iter: 20000
  sampler:
    batch_shuffle: true
    batch_size: [3, 22]
    frames_num_fixed: 20
    sample_type: fixed_unordered
    type: DiseaseTripletSampler
  transform:
    - type: BaseSilCuttingTransform
    - type: NoOperation
